"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var log_prefix_1 = require("@moonlord/log-prefix");
var fs = require("fs");
var fsWriteStream = fs.createWriteStream("./logs/test.log");
var prefixConsole = new log_prefix_1.default("[PrefixConsole]", fsWriteStream);
prefixConsole.log("[log] Hello %s", "World!");
prefixConsole.warn("[warn] Hello %s", "World!");
prefixConsole.error("[error] Hello %s", "World!");
prefixConsole.debug("[debug] Hello %s", "World!");
prefixConsole.info("[info] Hello %s", "World!");
prefixConsole.trace("[trace] Hello %s", "World!");
prefixConsole.table([{ a: 1, b: 2 }, { a: 3, b: 4 }]);
